import Hero from '@/components/Hero'
import Services from '@/components/Services'
import Layout from '@/layout/Layout'
import Head from 'next/head'
import { Parallax, Background } from 'react-parallax'


export default function Home() {

  return (
    <>
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      <Parallax
          
          bgImage='/assets/img/Backgrounds/Servicios.jpg'
          bgImageAlt="the dog"
          strength={-200}
      >
        
      <section className='h-[200px] '>

      </section>
    </Parallax>
    
      <Services/>
     </Layout>
    </>
  )
}
