
import Services from '@/pages/ServicesMain/Services'
import Layout from '@/layout/Layout'
import Head from 'next/head'
import { Parallax, Background } from 'react-parallax'
import Hero from './Hero'
import Offer from './Offer'
import Advisory from './Advisory'


export default function Home() {

  return (
    <>
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
          <Parallax
              
              bgImage='/assets/img/Backgrounds/low-poly-grid-haikei.svg'
              bgImageAlt="the dog"
              strength={-200}
              className='hidden md:grid'
          >
            
          <section className='h-[150px] '>

          </section>
        </Parallax>
        <Parallax
              
              bgImage='/assets/img/Backgrounds/low-poly-grid-haikei mobile.svg'
              bgImageAlt="the dog"
              strength={-200}
              className=' md:hidden'
          >
            
          <section className='h-[100px] '>

          </section>
        </Parallax>
    
      <Services/>
      <Offer/>
      <Advisory/>



     </Layout>
    </>
  )
}
